language: cpp
env:
  global:
    # CONVERITY_SCAN_TOKEN
    - secure: "xE7W9MrS4qf1usgtnVDrgNnZAUIuD6cq8MrvkbEuWVOTopmtbkMhZv60kQNIrFKUDcuv+ismIYBzymPh9EhjwNI1Dfu4jzasWvhlRFj0YTfz6F0+V2xjI9EJIXglfDBhJVhyf0Zngf0Czg1iQRRXuInZSStVdY+twsXqo6XL7Wc="
before_install:
 - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ saucy main universe"
 - sudo apt-get update -qq
 - sudo apt-get install -qq gperf libasio-dev libboost-dev libc-ares-dev libdb++-dev libpopt-dev libssl-dev perl libmysqlclient-dev libradiusclient-ng-dev libcppunit-dev autotools-dev libpcre3-dev libxerces-c-dev curl libcajun-dev
 - ./build/travis/coverity-setup
compiler:
  - gcc
script:
  - ./build/travis/bootstrap
  - ./build/travis/configure
  - ./build/travis/build
